# Generated by Django 3.2.25 on 2024-07-06 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_carplates_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='camera_config',
        ),
        migrations.AddField(
            model_name='cameraconfig',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='camera_config', to=settings.AUTH_USER_MODEL),
        ),
    ]
