# Generated by Django 3.2.25 on 2024-07-19 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20240706_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carplates',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='carplates',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='carplates',
            name='car_year',
        ),
        migrations.RemoveField(
            model_name='carplates',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='carplates',
            name='model',
        ),
        migrations.CreateModel(
            name='WashStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENTERED', 'Entered'), ('WASHING', 'Washing'), ('FINISHED', 'Finished')], default='ENTERED', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wash_status', to='projects.carplates')),
            ],
        ),
    ]
