# Generated by Django 3.2.25 on 2024-07-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20240718_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washstatus',
            name='status',
            field=models.CharField(choices=[('ENTERED', 'Entered'), ('WASHING', 'Washing'), ('FINISHED', 'Finished'), ('EXIT', 'Exit')], default='ENTERED', max_length=10),
        ),
    ]
