# Generated by Django 3.2.25 on 2024-07-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_customuser_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car_plate',
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ManyToManyField(related_name='queues', to='projects.Order')),
            ],
        ),
    ]
